import { Inter } from "next/font/google";
import "./globals.scss";
import Nav from "./components/nav";
import Footer from "./components/footer";
import ToTop from "./components/to-top";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car Rental",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <ToTop />
        <Footer />
      </body>
    </html>
  );
}
