
import "./globals.css";
import Nav from "./ui/nav/nav";
import ToTop from "./ui/to-top";
import Footer from "./ui/footer/footer";

export const metadata = {
  title: "Gramen Roofing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="top"></div>
        <ToTop />
        <Nav />

        {children}
        <Footer />
      </body>
    </html>
  );
}
