import { Inter } from "next/font/google";
import "./globals.scss";
import Footer from "./ui/footer/footer";
import Nav from "./ui/nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {/* <div className="col">
          <button className="btn-1">btn1</button>
          <button className="btn-2">btn2</button>
          <button className="btn-3">btn3</button>
          <button className="btn-4">btn4</button>
          <button className="btn-5">btn5</button>
          <button className="btn-6">btn6</button>
          <button className="btn-7">btn7</button>
          <button className="btn-8">btn8</button>
          <button className="btn-9">btn9</button>
          <button className="btn-10">btn10</button>
        </div> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
