import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./ui/footer/footer";
// import BackToTopButton from "./ui/buttons/back-to-top/back-to-top";
import Cart from "./ui/nav/Cart";
import Nav from "./ui/nav/Nav";
import Breadcrumbs from "./ui/breadcrumb/breadcrumb";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <div id="top"></div>
        {/* <Breadcrumbs /> */}
        {/* <Cart /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
