const COLUMNS = [
  {
    title: "Recently Added",
    items: [
      {
        name: "Lettuce",
        category: "Vegetable",
        updatedPrice: 0.75,
        oldPrice: 0.8,
        rating: 3.5,
        images: [
          "lettuce1.jpg",
          "lettuce2.jpg",
          "lettuce3.jpg",
          "lettuce4.jpg",
          "lettuce5.jpg",
        ],
      },
      {
        name: "Cucumber",
        category: "Vegetable",
        updatedPrice: 0.4,
        oldPrice: 0.45,
        rating: 4,
        images: [
          "cucumber1.jpg",
          "cucumber2.jpg",
          "cucumber3.jpg",
          "cucumber4.jpg",
          "cucumber5.jpg",
        ],
      },
      {
        name: "Garlic",
        category: "Vegetable",
        updatedPrice: 0.3,
        oldPrice: 0.4,
        rating: 4.5,
        images: [
          "garlic1.jpg",
          "garlic2.jpg",
          "garlic3.jpg",
          "garlic4.jpg",
          "garlic5.jpg",
        ],
      },
      {
        name: "Spinach",
        category: "Vegetable",
        updatedPrice: 0.85,
        oldPrice: 0.9,
        rating: 4,
        images: [
          "spinach1.jpg",
          "spinach2.jpg",
          "spinach3.jpg",
          "spinach4.jpg",
          "spinach5.jpg",
        ],
      },
      {
        name: "Milk",
        category: "Dairy",
        updatedPrice: 1.5,
        oldPrice: 1.6,
        rating: 4.5,
        images: [
          "milk1.jpg",
          "milk2.jpg",
          "milk3.jpg",
          "milk4.jpg",
          "milk5.jpg",
        ],
      },
      {
        name: "Eggs",
        category: "Dairy",
        updatedPrice: 2.1,
        oldPrice: 2.2,
        rating: 5,
        images: [
          "eggs1.jpg",
          "eggs2.jpg",
          "eggs3.jpg",
          "eggs4.jpg",
          "eggs5.jpg",
        ],
      },
    ],
  },
  {
    title: "Top selling",
    items: [
      {
        name: "Cheese",
        category: "Dairy",
        updatedPrice: 2.5,
        oldPrice: 2.7,
        rating: 4.5,
        images: [
          "cheese1.jpg",
          "cheese2.jpg",
          "cheese3.jpg",
          "cheese4.jpg",
          "cheese5.jpg",
        ],
      },
      {
        name: "Chicken",
        category: "Meat",
        updatedPrice: 5.0,
        oldPrice: 5.5,
        rating: 4,
        images: [
          "chicken1.jpg",
          "chicken2.jpg",
          "chicken3.jpg",
          "chicken4.jpg",
          "chicken5.jpg",
        ],
      },
      {
        name: "Beef",
        category: "Meat",
        updatedPrice: 7.0,
        oldPrice: 7.5,
        rating: 4.5,
        images: [
          "beef1.jpg",
          "beef2.jpg",
          "beef3.jpg",
          "beef4.jpg",
          "beef5.jpg",
        ],
      },
      {
        name: "Pork",
        category: "Meat",
        updatedPrice: 4.0,
        oldPrice: 4.3,
        rating: 4,
        images: [
          "pork1.jpg",
          "pork2.jpg",
          "pork3.jpg",
          "pork4.jpg",
          "pork5.jpg",
        ],
      },
      {
        name: "Fish",
        category: "Seafood",
        updatedPrice: 6.0,
        oldPrice: 6.5,
        rating: 4.5,
        images: [
          "fish1.jpg",
          "fish2.jpg",
          "fish3.jpg",
          "fish4.jpg",
          "fish5.jpg",
        ],
      },
      {
        name: "Shrimp",
        category: "Seafood",
        updatedPrice: 8.0,
        oldPrice: 8.5,
        rating: 5,
        images: [
          "shrimp1.jpg",
          "shrimp2.jpg",
          "shrimp3.jpg",
          "shrimp4.jpg",
          "shrimp5.jpg",
        ],
      },
    ],
  },
  {
    title: "Trending Products",
    items: [
      {
        name: "Rice",
        category: "Pantry",
        updatedPrice: 0.9,
        oldPrice: 1.0,
        rating: 4,
        images: [
          "rice1.jpg",
          "rice2.jpg",
          "rice3.jpg",
          "rice4.jpg",
          "rice5.jpg",
        ],
      },
      {
        name: "Beans",
        category: "Pantry",
        updatedPrice: 0.7,
        oldPrice: 0.85,
        rating: 4.5,
        images: [
          "beans1.jpg",
          "beans2.jpg",
          "beans3.jpg",
          "beans4.jpg",
          "beans5.jpg",
        ],
      },
      {
        name: "Sugar",
        category: "Pantry",
        updatedPrice: 0.5,
        oldPrice: 0.6,
        rating: 3.5,
        images: [
          "sugar1.jpg",
          "sugar2.jpg",
          "sugar3.jpg",
          "sugar4.jpg",
          "sugar5.jpg",
        ],
      },
      {
        name: "Salt",
        category: "Pantry",
        updatedPrice: 0.3,
        oldPrice: 0.35,
        rating: 4,
        images: [
          "salt1.jpg",
          "salt2.jpg",
          "salt3.jpg",
          "salt4.jpg",
          "salt5.jpg",
        ],
      },
      {
        name: "Pepper",
        category: "Pantry",
        updatedPrice: 2.0,
        oldPrice: 2.2,
        rating: 4.5,
        images: [
          "pepper1.jpg",
          "pepper2.jpg",
          "pepper3.jpg",
          "pepper4.jpg",
          "pepper5.jpg",
        ],
      },
    ],
  },
];

export default COLUMNS;
