import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "../ui/footer/footer";
// import BackToTopButton from "./ui/buttons/back-to-top/back-to-top";
import Cart from "../ui/nav/Cart";
import Nav from "../ui/nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>
    //     <Nav />
    //     <div id="top"></div>
    //     {/* <Cart />
    //     {children}
    //     <BackToTopButton />
    //     <Footer /> */}
    //   </body>
    // </html>
    <>{children}</>
  );
}
